### ISSUE TITLE
Monitor upstream channels

### ISSUE THREAD

**Issue by cryptoluks** [sp4rkie/docsis-cable-load-monitor#3]
Hi,

thanks for developing this tool. It works fine with the latest Raspberry OS and Raspberry Pi 4.

I want to pinpoint upstream issues (sometimes goes as low as 1 Mbits, normally 50 Mbits). What modifications are needed for this? Is this even possible?

Thanks again.

Cheers

**Comment by sp4rkie** [comment]
nice to hear it works for you. Upstream issues unfortunately can't be addressed by the given method due to the nature of DVB-C. 

Maybe it helps you to watch the (uncorrectable) error counters, modulation profiles, transmit levels of your modem?

**Comment by cryptoluks** [comment]
Ok I see.

Unfortunately, the TC4400 seems to only list errors for DL channels. But modulation profiles and transmit levels seem okay. Also, modulation is stable and does not never fallback to any of the lower modulations.

![image](https://user-images.githubusercontent.com/9020527/86508142-0efbe500-bdde-11ea-8f75-1f1965908ad7.png)

I found a pretty awesome sheet to interpret the values: [20180617_Pegelwerte.pdf](https://github.com/sp4rkie/docsis-cable-load-monitor/files/4872274/20180617_Pegelwerte.pdf)

**Comment by sp4rkie** [comment]
thanks for the pointers. I think the issue can be closed.
