### ISSUE TITLE
DOCSIS 3.1 DS

### ISSUE THREAD

**Issue by Technikte** [sp4rkie/docsis-cable-load-monitor#5]
Hi,
is it possible to use also DOCSIS 3.1 frequency with eg -qam 1024 ?

At the moment all freq with higher qam as 256 errors out..
```
{ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 202000000 -s 6952 -qam 1024; LD_PRELOAD=/opt/lib/libmediaclient.so timeout 1 dvbsnoop -adapter 0 -s bandwidth 8190 -n 80000; } 2>&1
## PID: 8190 (0x1ffe)   bad/total packets: 0/12632 (= 0.0%)   Avrg: 19093.998 kbit/s   
dvbtune/dvbsnoop fails for [ 202 ] [ 7 != 3 ], retrying...
```

```
root@raspberrypi:/home/pi/cableload# dvbtune -c 0 -f 202000000 -s 6952 -qam 1024
Invalid QAM rate: 1024
```

**Comment by sp4rkie** [comment]
current DVB-C hardware out there only supports 5 modulation modes: 16-QAM, 32-QAM, 64-QAM, 128-QAM, 256-QAM. For 1024-QAM support we have to wait for DVB-C2 hardware to be become  available.

**Comment by Technikte** [comment]
Alright, a litte hint in the readme about that fact should be good for all who follow me with this question.
